### ISSUE TITLE
[BUG] About the bug that the number of unread messages cannot be cleared

### ISSUE THREAD

**Issue by skywangch** [openimsdk/openim-sdk-core#556]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

The root of the issue is a bug in the mini-program side when calling OIMWS, but after reviewing the code, the core implementation was found in openim-sdk-core. The number of unread messages is displayed incorrectly, and even after successfully making a call to set the conversation as read, the message count does not reset and remains unchanged. Upon investigating the code at openim-sdk-core/v3@v3.5.1/internal/conversation_msg/read_drawing.go: 142, it was discovered that the unread message list is retrieved first, and then the message count table is cleared. However, if the unread message list is empty, it directly returns, and at this time, the count table might still be greater than zero (due to some inconsistencies). Unless a new unread message is received, the code to clear the count table is unreachable, and the count can never be reset to zero.

Suggestion: Execute the subsequent code regardless of whether the SQLite message table's unread messages are empty or not; do not return prematurely.

### Screenshots Link

相关代码：
<img width="686" alt="765e67d55aa54e8c5ff6674c24f2ec9" src="https://github.com/openimsdk/oimws/assets/28942093/dcd8c1b9-407e-48c8-8940-e17ea8881f07">

前端调用 markConversationMessageAsRead， 服务端 oimws 产生的日志：
<img width="1117" alt="0b132ca5f55b4c28e4fe9421a020a65" src="https://github.com/openimsdk/oimws/assets/28942093/986a0f0e-56a7-4ba6-a25d-5087ab9bbc71">

local db 消息表：
![image](https://github.com/openimsdk/openim-sdk-core/assets/28942093/eb5be8c1-47a7-4864-9b86-98b07be57bb2)

local db 会话表:
![image](https://github.com/openimsdk/openim-sdk-core/assets/28942093/3fd85fad-6a8b-4346-99c5-90c77ec01e28)

**Comment by skiffer-git** [comment]
The OIMWS will be phased out, and a new JavaScript SDK is currently under development. This upcoming SDK promises more advanced features and improved performance

**Comment by skiffer-git** [comment]
The root of the issue is a bug in the mini-program side when calling OIMWS, but after reviewing the code, the core implementation was found in openim-sdk-core. The number of unread messages is displayed incorrectly, and even after successfully making a call to set the conversation as read, the message count does not reset and remains unchanged. Upon investigating the code at openim-sdk-core/v3@v3.5.1/internal/conversation_msg/read_drawing.go: 142, it was discovered that the unread message list is retrieved first, and then the message count table is cleared. However, if the unread message list is empty, it directly returns, and at this time, the count table might still be greater than zero (due to some inconsistencies). Unless a new unread message is received, the code to clear the count table is unreachable, and the count can never be reset to zero.

Suggestion: Execute the subsequent code regardless of whether the SQLite message table's unread messages are empty or not; do not return prematurely.
